### PR TITLE
Fixed incorrect loop iteration for Slide 16 in 3_wara_reports_generator.ps1

### PR DESCRIPTION
**Pull request by yahanda**
# Overview/Summary

The number of loops is incorrect. "Azure SQL not configure to scale automatically" in line 5 of "Azure Resouces Key High Impact issues" on the ppt slide p16 is always not replaced.

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. To fix the loop count, `$count -lt 5` was replaced with `$count -le 5`.

### Breaking Changes

1. _Replace me_
2. _Replace me_

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by Claudio-Merola — APPROVED** [review]
Valid fix

**Review by oZakari — APPROVED** [review]
LGTM

**Comment by oZakari** [comment]
@yahanda can you resolve the merge conflict please and then we can merge.

**Comment by yahanda** [comment]
@oZakari thank you for reviewing the PR. I have resolved the merge conflict.

**Pull request merged**
