### PR TITLE
query and instructions for "Configure minimal logging and retention of logs"

### PR DESCRIPTION
**Pull request by ReneHezser**
# Overview/Summary

The recommendation cannot fully be checked with a query. But it lists all workspaces to check them.
image

## Related Issues/Work Items

[AB#32800](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32800)

## This PR fixes/adds/changes/removes

1. adds a resource graph query for all workspaces

### Breaking Changes

1. none

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by ReneHezser** [comment]
> ..., it identifies a set of resources for further review. This is not in line with the current ARG query expectations ...

If you have 5 services, like in my example above, what is the expectation? Copying all the data to Excel? How do you identify the talking points? Wouldn't it be easier to have them already filled and delete the ones that are compliant? That, btw, goes for all recommendations.

**Comment by ejhenry** [comment]
> > ..., it identifies a set of resources for further review. This is not in line with the current ARG query expectations ...
> 
> If you have 5 services, like in my example above, what is the expectation? Copying all the data to Excel? How do you identify the talking points? Wouldn't it be easier to have them already filled and delete the ones that are compliant? That, btw, goes for all recommendations.

For those recommendations that cannot be validated with ARG, the automation tooling will still add the recommendation to the action plan spreadsheet. If there are resources for which the recommendation is applicable, the resource information will need to be added to the Impacted Resources tab of the spreadsheet. Perhaps deleting is easier, but this is not a heavy lift.

We have decided on this approach as it ensures we are not making inaccurate recommendations as a result of false positives from our ARG queries.

If we cannot get the query to a point where it accurately identifies only the resources for which this recommendation is applicable, this PR should be closed.

**Comment by ReneHezser** [comment]
Thanks for elaborating. In that case I would remove the recommendation.
The current title *Configure minimal logging and retention of logs* does not reflect the description to check for retention of logs. Removing it leaves with *Configure the retention of logs*, which is not resiliency. What do you think @ejhenry?

**Comment by ejhenry** [comment]
> Thanks for elaborating. In that case I would remove the recommendation. The current title _Configure minimal logging and retention of logs_ does not reflect the description to check for retention of logs. Removing it leaves with _Configure the retention of logs_, which is not resiliency. What do you think @ejhenry?

Agree on removing. Let's follow up with the DRI, since it is PG verified, to confirm.

**Comment by ejhenry** [comment]
> > Thanks for elaborating. In that case I would remove the recommendation. The current title _Configure minimal logging and retention of logs_ does not reflect the description to check for retention of logs. Removing it leaves with _Configure the retention of logs_, which is not resiliency. What do you think @ejhenry?
> 
> Agree on removing. Let's follow up with the DRI, since it is PG verified, to confirm.

@ReneHezser we are good to remove the recommendation. Would you like to make the change in this PR, or close and handle in a separate PR.

**Comment by ReneHezser** [comment]
@ejhenry I modified this PR to remove the recommendation.

**Review by ejhenry — APPROVED** [review]
thanks @ReneHezser, LGTM 👍

**Review by oZakari — APPROVED** [review]

**Pull request merged**
