### PR TITLE
fix: Patch/dev tools 10 25 2024

### LINKED ISSUE #295: 🪲 Bug Report - Failed insert charts from Excel on slide 17
## Describe the bug

Inserting charts failed from the Excel file on the slide 17 that was generated by 3_wara_reports_generator.ps1 (version 2.0.5).

## To Reproduce

1. Run the `1_wara_collector.ps1`.
2. Run the `2_wara_data_analyzer.ps1`.
3. Run the `3_wara_reports_generator.ps1`.

## Expected behaviour

The charts are inserted from the Excel file.

## Screenshots 📷

image

## Additional context

When processing the slide 17, `$Global:Ex` was null.

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/95246b37700ceb141ab7dda100900416f64738db/tools/3_wara_reports_generator.ps1#L449

So, doing copy and paste the charts will fail.

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/95246b37700ceb141ab7dda100900416f64738db/tools/3_wara_reports_generator.ps1#L455-L457

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/95246b37700ceb141ab7dda100900416f64738db/tools/3_wara_reports_generator.ps1#L471-L473

**Additional notes:**

The code of slide manipulation needs refactoring. It has unnecessary complexity. It will lead to mis-modification and increase maintenance efforts.

Current:
https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/95246b37700ceb141ab7dda100900416f64738db/tools/3_wara_reports_generator.ps1#L443-L483

Example:

```powershell
$Slide17 = $pres.Slides(17)

# Update the notice label
$noticeLabelName = 'TextBox 1'
$TargetShape = $Slide17.Shapes($noticeLabelName)
$TargetShape.TextFrame.TextRange.Text = $AUTOMESSAGE

if ($CoreDebugging) { ('PPT_Thread - ' + (get-date -Format 'yyyy-MM-dd HH:mm:ss') + ' - Info - Editing Slide 17 - Looking Charts in Excel File...') | Out-File -FilePath $LogFile -Append }
$chartWorksheetName = 'Charts'
$WS2 = $Global:Ex.Worksheets($chartWorksheetName)

# Copy "Per services/WAF area" chart from the Excel file.
if ($CoreDebugging) { ('PPT_Thread - ' + (get-date -Format 'yyyy-MM-dd HH:mm:ss') + ' - Info - Editing Slide 17 - Replacing Chart 1..') | Out-File -FilePath $LogFile -Append }
$sampleChartNamePerServicesWafArea = 'Chart 2'
$chartNamePerServicesWafArea = 'ChartP0'
$Slide17.Shapes($sampleChartNamePerServicesWafArea).Delete()
if ($Heavy) {Start-Sleep -Milliseconds 500} else {Start-Sleep -Milliseconds 100}
$WS2.ChartObjects($chartNamePerServicesWafArea).Copy()
if ($Heavy) {Start-Sleep -Milliseconds 500} else {Start-Sleep -Milliseconds 100}
[void] $Slide17.Shapes.Paste()
Start-Sleep 2
$targetShape = $Slide17.Shapes($chartNamePerServicesWafArea)
$targetShape.IncrementLeft(240)

# Copy "Per resiliency category" chart from the Excel file.
if ($CoreDebugging) { ('PPT_Thread - ' + (get-date -Format 'yyyy-MM-dd HH:mm:ss') + ' - Info - Editing Slide 17 - Replacing Chart 2..') | Out-File -FilePath $LogFile -Append }
$sampleChartNamePerResiliencyCategory = 'Chart 4'
$chartNamePerResiliencyCategory = 'ChartP1'
$Slide17.Shapes($sampleChartNamePerResiliencyCategory).Delete()
if ($Heavy) {Start-Sleep -Milliseconds 500} else {Start-Sleep -Milliseconds 100}
$WS2.ChartObjects($chartNamePerResiliencyCategory).Copy()
if ($Heavy) {Start-Sleep -Milliseconds 500} else {Start-Sleep -Milliseconds 100}
[void] $Slide17.Shapes.Paste()
Start-Sleep 2
$targetShape = $Slide17.Shapes($chartNamePerResiliencyCategory)
$targetShape.IncrementLeft(-260)
$targetShape.IncrementTop(45)
```

### LINKED ISSUE #360: 🪲 Bug Report - Advisor versus APRL category naming correction - High Availability
## Describe the bug

The High Availability Advisor recommendations in generated Excel are categorized as "HighAvailability" while the APRL generated recommendations use "High Availability" with a space.  It create duplicate category in the Pivot Charts and PPT.

## To Reproduce

Steps to reproduce the behaviour:

1. Run [2_wara_data_analyzer.ps1](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/main/tools/2_wara_data_analyzer.ps1) on Json created by [1_wara_collector.ps1](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/main/tools/1_wara_collector.ps1)
2. Check Pivot table in the generated Excel, it shows both categories as seperate lines in the table.

## Expected behaviour

Both refer to one category so should be combined together either by changing APRL convention or Advisor.

## Screenshots 📷
image

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Additional context

Anything else we should know to help us troubleshoot this bug?

### PR DESCRIPTION
**Pull request by kpoineal**
# Overview/Summary

### 1_wara_collector.ps1
- Fix duplicated "Microsoft." in resource type in output messages
- Add RepoUrl parameter for custom ARPL repo (This is a temporary solution since the Japan team has a fork of the APRL repo to use Japanese characters in their artifacts. This will be addressed in the refactor through localization)
- Fixed issue where too many lines between configuration sections would cause an error when capturing the correct items in the section.
- Fixed issue where blank sections in the configuration file would cause the properties to be blank or incorrect.
- Fixed issue where advisor recommendations object would be reset if more than one implicit subscriptionid was present.

### 2_wara_data_analyzer.ps1
- Fixed line-breaks in learnMoreLink URLs.
- Fixed issue with Advisor recommendations being excluded if there was no corresponding APRL recommendation or recommendationTypeId field for the APRL recommendation.
- Fixed the duplicate High Availability category in the Pivot Charts.

### 3_wara_reports_generator.ps1
- Fixed full file name issues when specifying the location of the word or ppt templates.

## Related Issues/Work Items

Fixes #295
Fixes #360 

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by ejhenry — APPROVED** [review]
LGTM thanks @kpoineal!

**Review by tksh164 — COMMENTED** [review]
- Issue #295 is not yet fixed.
- 3_wara_reports_generator.ps1 has been updated, but the script version has not.
    - Created a PR to this PR's branch #489

**Comment by kpoineal** [comment]
I thought it we fixed it in devtools? I’ll get it taken of.Sent from my iPhoneOn Oct 26, 2024, at 12:13 AM, Takeshi Katano ***@***.***> wrote:﻿
@tksh164 commented on this pull request.


Issue #295 is not yet fixed.
3_wara_reports_generator.ps1 has been updated, but the script version has not.

**Comment by tksh164** [comment]
@kpoineal - Issue #295 is not yet fixed in devtools. I confirmed by checked out this branch (patch/dev-tools-10-25-2024) then run the scripts. Issue #295 is still existing.

**Comment by kpoineal** [comment]
> @kpoineal - You intended #360? This issue was fixed on dev-tools branch and not yet merged into main. Also #360 is not mentioned in this PR's notes but included in this PR.

I thought I included it but I'll add it in.

The issue with #295 is because of a different bug that we just found with the path resolution using something like:
```powershell
.\3_wara_reports_generator.ps1 -ExcelFile ".\WARA Action Plan.xlsx"
```
The script wouldn't find the action plan unless we used the full path. I've adjusted this so that it accepts short or long paths.

The third script only uses the excel com instance for copying the charts into the word/ppt files. It failed when passed a short name. It was working with a full name, so we've adjusted the script to compensate.

**Review by tksh164 — APPROVED** [review]
LGTM

**Review by ejhenry — APPROVED** [review]

**Review by ejhenry — APPROVED** [review]

**Review by rodrigosantosms — DISMISSED** [review]

**Review by ejhenry — APPROVED** [review]

**Review by rodrigosantosms — APPROVED** [review]
approved

**Pull request merged**
