### PR TITLE
Added recommendation for ExR Circuit

### PR DESCRIPTION
**Pull request by khushal08**
# Overview/Summary

ExpressRoute Circuit has recently started supporting traffic collector. Added recommendation for ERTC. 

### Breaking Changes

NA

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by ejhenry — COMMENTED** [review]
@khushal08 the recommendation in this PR appears to be redundant with the existing Traffic Collector recommendation. Can we close this PR or is there a difference between the two?

**Comment by khushal08** [comment]
@ejhenry I disagree. The first one is specific for ExR "Direct" circuits and the second is about "Provider" circuits. Other option is we can merge them to talk about both. thoughts?

**Comment by ejhenry** [comment]
> @ejhenry I disagree. The first one is specific for ExR "Direct" circuits and the second is about "Provider" circuits. Other option is we can merge them to talk about both. thoughts?

Ah yes, I now see the reference to "Direct" in the existing recommendation. Considering the recommendations are otherwise identical and reference the same Learn More link, perhaps a single recommendation could work for both. I think we need to determine which option is better for the CSA doing manual validation since neither have ARG queries. Or, if we think we can develop ARG queries, could a single query suffice for both scenarios?

cc @Azure/aprl-networking

**Comment by oZakari** [comment]
@khushal08, can you please correct the yaml syntax error for the GUID. For consistency, all letters need to be capatalized for the GUIDs.

**Comment by ehaslett** [comment]
> > @ejhenry I disagree. The first one is specific for ExR "Direct" circuits and the second is about "Provider" circuits. Other option is we can merge them to talk about both. thoughts?
> 
> Ah yes, I now see the reference to "Direct" in the existing recommendation. Considering the recommendations are otherwise identical and reference the same Learn More link, perhaps a single recommendation could work for both. I think we need to determine which option is better for the CSA doing manual validation since neither have ARG queries. Or, if we think we can develop ARG queries, could a single query suffice for both scenarios?
> 
> cc @Azure/aprl-networking

I agree with the single recommendation approach since the content is identical, with the caveat that a single query would need to cover both scenarios.

**Comment by khushal08** [comment]
@ejhenry Consolidated and updated as per feedback. Please review

**Review by ehaslett — APPROVED** [review]
LGTM - thanks @khushal08

**Comment by khushal08** [comment]
@ejhenry Can you please approve?

**Review by oZakari — APPROVED** [review]
LGTM

**Pull request merged**
