### PR TITLE
fixes query for CosmosDB consistency level

### PR DESCRIPTION
**Pull request by ReneHezser**
# Overview/Summary

Adds the query to check the consistency model.
image

## Related Issues/Work Items

AB#32801

## This PR fixes/adds/changes/removes

1. Add the resource graph query

### Breaking Changes

none

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by Dost2010** [comment]
@ReneHezser
The recommendation to which this ARG query is associated with does not explicitly say which consistency level to choose. Would it be nice to include more prescriptive guidance to align it with ARG query recommendation? for example choosing consistency level  other than session?

**Comment by ReneHezser** [comment]
> @ReneHezser The recommendation to which this ARG query is associated with does not explicitly say which consistency level to choose. Would it be nice to include more prescriptive guidance to align it with ARG query recommendation? for example choosing consistency level other than session?

@Dost2010 The recommendation states *Use Session consistency unless stronger is needed*. That's why I used that value. I think it is a good starting point to see which accounts exist and discuss. If you feel this is not right, we should consider removing the recommendation.

**Comment by Dost2010** [comment]
@ReneHezser 
database consistency is application data governance issue, and it does not affect reliability of infrastructure. Usually, application designer and data team take decision based on their application specific use cases and hence it is setup appropriately. We should not be enforcing one consistency over the other and I believe this recommendation should be removed.  Thought?

**Comment by ReneHezser** [comment]
I agree @Dost2010. Let's remove it.

**Comment by Dost2010** [comment]
@ReneHezser 
Would you submit removal change? alternatively give me access to branch and i can make changes. It is to ensure that this conversation go along with the commits.

**Review by Dost2010 — APPROVED** [review]

**Review by ejhenry — APPROVED** [review]

**Pull request merged**
