### PR TITLE
Added "Deploy zone-redundant ExpressRoute gateways with zone-redundant Public IP(s)" in Network\virtualNetworkGateways

### PR DESCRIPTION
**Pull request by cbezenco**
# Overview/Summary

Added "Deploy zone-redundant ExpressRoute gateways with zone-redundant Public IP(s)" in Network\virtualNetworkGateways
Description/KQL is based on slight update on "Deploy zone-redundant VPN gateways with zone-redundant Public IP(s)" 4bae5a28-5cf4-40d9-bcf1-623d28f6d917

## Related Issues/Work Items

NA 

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. Add new recommendation for ExpressRoute resiliency check

### Breaking Changes

NA

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x
Screenshot 2024-05-24 203823
] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by rodrigosantosms** [comment]
@cbezenco  @ejhenry  We already have recommendations for zone-redundant for both, ExpressRoute GW and Public IPs.

EXR - https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/virtualNetworkGateways/#use-zone-redundant-expressroute-gateway-skus

PIP - https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/publicIPAddresses/#use-standard-sku-and-zone-redundant-ips-when-applicable

I recommend we update the "Long Description" of the ExpressRoute Gateway recommendation to include that Users should also check the Public IP, we could even update the Query, however, there is query for that too.

And then for the Public IP we could validate if the query is capturing PIPs no in zone-redundant when associated with GWs too.

**Comment by zebak007** [comment]
It does not make sense to me for the following reasons:

1. I don't understand why you have a rule for VPN gateway Zone redundant PIP  in the reliability library and not for ExpressRoute Gateway. (see https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/virtualNetworkGateways/#deploy-zone-redundant-vpn-gateways-with-zone-redundant-public-ips). We need to be consistent here.

2. EXR - https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/virtualNetworkGateways/#use-zone-redundant-expressroute-gateway-skus is not enough. I have lost 2 hours trying to understand why my customer ExpressRoute gateway was reported as not Zone enabled in CXobserve while it was deployed with an AZ enabled SKU. 

3. Keeping your approach means that my customer ExpressRoute Gateway PIP is lost among 9 others PIP that needs remediation which means that I don't have an easy way to put the fact that ExpressRoute needs immediate attention by looking at the spreadseeh and recommendations. 

4. Finally main issue is that this PIP is not like the other PIP. You cannot remediate this PIP as it is part of the ExpressRoute Gateay. Based on my understanding customer will need to redeploy their ExpressRoute gateway, they cannot just change the PIP on the fly...

Do not hesitate to ping me so I can go deeper on this so I can convince you to review your stance.

**Comment by cbezenco** [comment]
> It does not make sense to me for the following reasons:
> 
> 1. I don't understand why you have a rule for VPN gateway Zone redundant PIP  in the reliability library and not for ExpressRoute Gateway. (see https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/virtualNetworkGateways/#deploy-zone-redundant-vpn-gateways-with-zone-redundant-public-ips). We need to be consistent here.
> 2. EXR - https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/virtualNetworkGateways/#use-zone-redundant-expressroute-gateway-skus is not enough. I have lost 2 hours trying to understand why my customer ExpressRoute gateway was reported as not Zone enabled in CXobserve while it was deployed with an AZ enabled SKU.
> 3. Keeping your approach means that my customer ExpressRoute Gateway PIP is lost among 9 others PIP that needs remediation which means that I don't have an easy way to put the fact that ExpressRoute needs immediate attention by looking at the spreadseeh and recommendations.
> 4. Finally main issue is that this PIP is not like the other PIP. You cannot remediate this PIP as it is part of the ExpressRoute Gateay. Based on my understanding customer will need to redeploy their ExpressRoute gateway, they cannot just change the PIP on the fly...
> 
> Do not hesitate to ping me so I can go deeper on this so I can convince you to review your stance.

Based on our call, I am good with the approach you proposed.

**Review by jimays-avila — APPROVED** [review]
Looks good.

**Comment by oZakari** [comment]
@rodrigosantosms and @ehaslett looks like Jimmy approved. There also appears to have been a call that happened to discuss this, but not sure if either of you were on it? 

Please let us know if we are good with merging at this point. Thanks!

**Comment by cbezenco** [comment]
sorry I am OOF for 3 weeks. Rodrigo wants simplify/reduce the number of rules. 
Redundant IP check to be included in the https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/virtualNetworkGateways/#use-zone-redundant-expressroute-gateway-skus

Similarly the entries for VPN Gateways below should be merged:
https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/virtualNetworkGateways/#choose-a-zone-redundant-vpn-gateway
https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/virtualNetworkGateways/#deploy-zone-redundant-vpn-gateways-with-zone-redundant-public-ips

Unfortunately I could not work on this as I am about to switch off for 3 weeks break.

**Comment by ehaslett** [comment]
> @rodrigosantosms and @ehaslett looks like Jimmy approved. There also appears to have been a call that happened to discuss this, but not sure if either of you were on it?
> 
> Please let us know if we are good with merging at this point. Thanks!

I don't recall if I was part of that discussion, I think probably not. In any case, Christian's comments about merging PIP with the zone-redundant SKUs guidance sound like the way forward.

**Comment by ehaslett** [comment]
> sorry I am OOF for 3 weeks. Rodrigo wants simplify/reduce the number of rules. Redundant IP check to be included in the https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/virtualNetworkGateways/#use-zone-redundant-expressroute-gateway-skus
> 
> Similarly the entries for VPN Gateways below should be merged: https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/virtualNetworkGateways/#choose-a-zone-redundant-vpn-gateway https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/virtualNetworkGateways/#deploy-zone-redundant-vpn-gateways-with-zone-redundant-public-ips
> 
> Unfortunately I could not work on this as I am about to switch off for 3 weeks break.

@JefferyMitchell - should we track this revised approach above with a user story? As Christian is out for 3 weeks, this could find another owner in the interim.

**Pull request merged**
