### PR TITLE
fix: Fix duplicated "Microsoft." in resource type in output messages

### PR DESCRIPTION
**Pull request by tksh164**
# Overview/Summary

Fixed `Microsoft.microsoft` in resource type in output messages.

image

## Related Issues/Work Items

None

### Breaking Changes

None

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ ] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

# Screenshot

image

### CODE REVIEW

**Review by oZakari — APPROVED** [review]
LGTM

**Comment by tksh164** [comment]
@caseywatson @kpoineal @Claudio-Merola Would you be willing to review this PR? This PR has been over 3 weeks with no reviews. Thanks.

**Review by oZakari — APPROVED** [review]

**Comment by ejhenry** [comment]
@kpoineal @Claudio-Merola please review

**Comment by kpoineal** [comment]
@tksh164 Hey sorry about the long wait to review this. Is this still occurring? I haven't seen this behavior with the most recent updates.

**Comment by tksh164** [comment]
@kpoineal Yes, this still exist in the latest script. The released and in dev-tools both scripts.

image

**Comment by kpoineal** [comment]
Approved.

**Pull request merged**
