### PR TITLE
docs: Update AVD recommendations

### PR DESCRIPTION
**Pull request by moisesjgomez**
# Overview/Summary

Update 99bf5c94-aa68-4bb3-8b7f-45d1c5f09b5d 
Update d61f6ee8-de1b-4fd9-9ce3-316cfe11ee05

cc: @swathibhat1 

https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_workitems/edit/36374

### Breaking Changes

1. _Replace me_
2. _Replace me_

## As part of this pull request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by ejhenry** [comment]
Hi @moisesjgomez, there are two failing checks for the PR that need to be addressed. Let me know if you have any questions about the required changes.

**Comment by moisesjgomez** [comment]
@ejhenry checks have been resolved. Thank you!

**Review by ejhenry — APPROVED** [review]
thanks @moisesjgomez LGTM 👍

**Comment by ejhenry** [comment]
@Azure/aprl-avd please review

**Review by swathibhat1 — APPROVED** [review]
Reviewed. Can be merged. Thank you.

**Pull request merged**
