### PR TITLE
refactor: Remove unused KQL query and recommendation for Service Bus

### PR DESCRIPTION
**Pull request by codebytes**
# Overview/Summary

Removing un-needed recommendation. Service bus will always be zone redundant where possible and the zoneredundant property will be removed.

### Breaking Changes

1. remove recommendation 20057905-262c-49fe-a9be-49f423afb359

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by ejhenry** [comment]
Hi @codebytes, this recommendation and associated ARG query are intended to identify instances of Service Bus namespaces that are not zone redundant. This could be because they are not using the Premium sku and/or they are not in a region that supports AZs. For both scenarios we want to return the recommendation to use AZs.

**Comment by codebytes** [comment]
After speaking with PG yesterday, all instances of SB will be zone redundant where possible. this is already updated in the documentation and this recommendation is no longer valid.
https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-outages-disasters#availability-zones

**Review by oZakari — APPROVED** [review]
After reviewing the documentation further, removing this recommendation makes sense to me. Unlike Event Hub namespaces, the availabilityZone property in the resource schema doesn’t actually control whether availability zones are enabled. Additionally, setting the availabilityZone property to false can still lead to incorrect configurations. Since this property will eventually be deprecated, the query won’t work with newer API versions either.
image

**Comment by ejhenry** [comment]
Thanks for the PR @codebytes, we are going to keep a recommendation in the library until the migration is complete.

**Comment by codebytes** [comment]
Ok, but per the PM of service bus:
Can you please confirm we want to remove the advisor recommendation around AZ for Service Bus as its not longer controllable by the user.

Yes, confirmed. The property that was used for this is ignored now, so customer is no longer in control of this.

**Pull request closed without merging**
