### PR TITLE
AVD recommendations impact fixes

### PR DESCRIPTION
**Pull request by danycontre**
# Overview/Summary

AVD recommendations impact fixes

## Related Issues/Work Items

N/A

## This PR fixes/adds/changes/removes

1. Fixing the impact level of 4 items that were changed by mistake during V1 to V2 conversion and applied in the latest PR we submitted.

### Breaking Changes

1. None

## As part of this pull request I have

- [ x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x ] Ensured PR tests are passing
- [ x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by danycontre** [comment]
@swathibhat1

**Review by oZakari — APPROVED** [review]
LGTM

**Review by ejhenry — APPROVED** [review]
LGTM

**Comment by danycontre** [comment]
Hey folks, please let us know if there is anything pending on our side.

**Comment by oZakari** [comment]
Hey @danycontre, just waiting from someone on your team to approve as well.

image

**Review by yshafner — APPROVED** [review]
Great work!

**Review by moisesjgomez — APPROVED** [review]

**Pull request merged**
