### PR TITLE
feat: Add SQL/ManagedInstances and StreamAnalyticsJobs and Fix ExpressRoute Circuits

### PR DESCRIPTION
**Pull request by rodrigosantosms**
# Overview/Summary

Feat: Add SQL/ManagedInstances and StreamAnalyticsJobs and Fix ExpressRoute Circuits

### CODE REVIEW

**Comment by rodrigosantosms** [comment]
@ehaslett could you please review the networking change? That is a simple one requested by Ed.
@ejhenry  or @oZakari  could you review from APRL perspective the SQLMI and Streaming Analytics? Once approved I'll work with Shweta to submit to Data and AI DRIs for PG Review approval, and continuation.

**Review by oZakari — APPROVED** [review]
LGTM

**Comment by ehaslett** [comment]
> @ehaslett could you please review the networking change? That is a simple one requested by Ed. @ejhenry or @oZakari could you review from APRL perspective the SQLMI and Streaming Analytics? Once approved I'll work with Shweta to submit to Data and AI DRIs for PG Review approval, and continuation.

Network kql files LGTM

**Review by ehaslett — APPROVED** [review]
Network KQL files LGTM

**Pull request merged**
