### PR TITLE
Renamed query file to have a `.kql` suffix

### LINKED ISSUE #159: 🪲 Bug Report - Missing `.kql` suffix in file `9e39919b-78af-4a0b-b70f-c548dae97c25`
## Describe the bug

Missing `.kql` suffix in file `azure-resources/RecoveryServices/vaults/kql/9e39919b-78af-4a0b-b70f-c548dae97c25`

/cc @alisakina99

### PR DESCRIPTION
**Pull request by chgeuer**
Closes #159 and #161

/cc @alisakina99 @oZakari

### CODE REVIEW

**Review by ejhenry — CHANGES_REQUESTED** [review]
Thanks @chgeuer. Looks like the kql file for this virtualNetworkGateways recommendation had been placed under storageAccounts. Can you remove the kql file from storageAccounts now that your PR is placing the file in the proper location?

image

**Comment by chgeuer** [comment]
Hi @ejhenry, should be done now.

**Review by chgeuer — COMMENTED** [review]
Done.

**Review by chgeuer — COMMENTED** [review]
Done.

**Review by ejhenry — APPROVED** [review]
LGTM

**Review by Dost2010 — APPROVED** [review]

**Pull request merged**
