### PR TITLE
Add a new VM recommendation for ZRS Disk

### PR DESCRIPTION
**Pull request by pinyuko**
# Overview/Summary

Added a new VM recommendation and query for "Use ZRS Disks or Protect LRS Disks from Availability Zone Failure" (fa0cf4f5-0b21-47b7-89a9-ee936f193ce1) after discussion and verification with Disk PM Bea Vincent and Ryan Draper.

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. Added a new VM recommendation for "Use ZRS Disks or Protect LRS Disks from Availability Zone Failure" (fa0cf4f5-0b21-47b7-89a9-ee936f193ce1)
2. Added query for "Use ZRS Disks or Protect LRS Disks from Availability Zone Failure" (fa0cf4f5-0b21-47b7-89a9-ee936f193ce1) 

### Breaking Changes

N/A

## As part of this pull request I have

- [X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [X] Ensured PR tests are passing
- [X] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by pinyuko** [comment]
Screenshot of ARG query

image

**Review by ejhenry — COMMENTED** [review]
Thanks for the contribution @pinyuko! Just a couple items to address:

- Please ensure the ARG query output matches the column names in the contribution guide
- Please ensure the longDescription is 300 characters or less
- Please include only 1 learnMoreLink

**Comment by pinyuko** [comment]
New screenshot for ARG
image

**Review by ejhenry — APPROVED** [review]
LGTM

**Review by oZakari — APPROVED** [review]
LGTM

**Pull request merged**
