### PR TITLE
Update NAT GW Recommendations

### PR DESCRIPTION
**Pull request by rozkurt**
# Overview/Summary

I created recommendations for NAT GW resource type

## Related Issues/Work Items

AB#34725

image

## This PR fixes/adds/changes/removes

1. Adds recommendations for NAT Gateway

### Breaking Changes

1. N/A

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by rodrigosantosms — CHANGES_REQUESTED** [review]
Could we tweak recommendation 1 to be more actionable? Is there a metric we would like to recommend customers to monitor to help them decide when they should Scale? In APRL we need more "Actionable" "Verifiable" recommendations.

For Recommendation 2, we could drop it, this is something configurable from the other services perspective not from NAT GW perspective.

For Recommendation 3, Let's be more specific, which Counters and Thresholds (Available in AMBA) are High or Medium or Low and should be present?

WOuld you think we could add recommendations around Zones x Zonal?

**Comment by rozkurt** [comment]
@rodrigosantosms thanks for the feedback! I updated the recommendations accordingly and I'd appreciate if you could review again and let me know!

**Comment by oZakari** [comment]
Hi @rozkurt, thanks for the contribution. Can you please correct the lint errors for the editorconfig.

image

**Comment by rozkurt** [comment]
@oZakari I just fixed errors with linting!

**Review by oZakari — APPROVED** [review]
LGTM, thank you for your contribution @rozkurt!

**Comment by oZakari** [comment]
@Azure/aprl-networking, please re-review.

**Review by JefferyMitchell — APPROVED** [review]

**Comment by JefferyMitchell** [comment]
The requested updates have been made hoping we can merge this.

**Pull request merged**
