### PR TITLE
fix: Remove "Configure NSG Flow Logs" deprecated recommendation + references

### PR DESCRIPTION
**Pull request by jdmsoss**
# Overview/Summary

On 30 September 2027, NSG flow logs will be retired.

## As part of this pull request I have

- [X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by ehaslett** [comment]
Do we have an official policy for APRL about when to remove guidance for services that are being retired? And how soon or not to remove the guidance? Currently I don't see a public announcement about the retirement. 

That is:
Do we remove APRL guidance ASAP after retirement is announced? Or prior to the announcement?
Do we remove APRL guidance N days/months/years in advance of the retirement, but no sooner? (In this case it looks like 3 years)

**Review by ehaslett — CHANGES_REQUESTED** [review]
Do we have an official policy for APRL about when to remove guidance for services that are being retired? And how soon or not to remove the guidance? Currently I don't see a public announcement about the retirement.

That is:
Do we remove APRL guidance ASAP after retirement is announced? Or prior to the announcement?
Do we remove APRL guidance N days/months/years in advance of the retirement, but no sooner? (In this case it looks like 3 years)

**Comment by tksh164** [comment]
> Currently I don't see a public announcement about the retirement.

The announcement was delivered via Health advisories in Service Health.

https://app.azure.com/h/4NBJ-DQ0/ebb993

image

**Comment by tksh164** [comment]
Retirement: Network security group flow logs in Azure Network Watcher will be retired
https://azure.microsoft.com/en-us/updates/v2/Azure-NSG-flow-logs-Retirement

**Comment by ehaslett** [comment]
> Do we have an official policy for APRL about when to remove guidance for services that are being retired? And how soon or not to remove the guidance? Currently I don't see a public announcement about the retirement.
> 
> That is: Do we remove APRL guidance ASAP after retirement is announced? Or prior to the announcement? Do we remove APRL guidance N days/months/years in advance of the retirement, but no sooner? (In this case it looks like 3 years)

I recommend that as part of this change, new guidance under Virtual Networks be put in place for the configuration of Vnet flow logs.

**Comment by jdmsoss** [comment]
> > Do we have an official policy for APRL about when to remove guidance for services that are being retired? And how soon or not to remove the guidance? Currently I don't see a public announcement about the retirement.
> > That is: Do we remove APRL guidance ASAP after retirement is announced? Or prior to the announcement? Do we remove APRL guidance N days/months/years in advance of the retirement, but no sooner? (In this case it looks like 3 years)
> 
> I recommend that as part of this change, new guidance under Virtual Networks be put in place for the configuration of Vnet flow logs.

It already exists, but under Network Watcher component 👉 [Enable NSG and Virtual Network Flow Logs](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/networkWatchers/#enable-network-security-group-and-virtual-network-flow-logs)

That's why I didn't suggest it, to avoid duplicates.

**Comment by oZakari** [comment]
@jdmsoss I created a PR against your branch to keep the recommendation in the repo in Disabled state so it won't show up in site or be added in WARA scripts until it is fully deprecated. That way, someone doesn't accidentally add it back in another PR.

cc: @ehaslett

**Comment by jdmsoss** [comment]
> @jdmsoss I created a PR against your branch to keep the recommendation in the repo in Disabled state so it won't show up in site or be added in WARA scripts until it is fully deprecated. That way, someone doesn't accidentally add it back in another PR.
> 
> cc: @ehaslett

@oZakari I'm not sure to understand this one. If you submit back a PR on my forked repo main branch, won't that create a diff with the APRL upstream repo main branch? 
Thanks for enlightening me on this practice or if you have any docs that correspond to this!

**Comment by oZakari** [comment]
Hey @jdmsoss, thanks for calling that out. I didn't realize I was targeting your main branch, so I corrected it to the nsg-flowlogs branch associated to this PR. Please review and merge if you can now.

**Review by ehaslett — APPROVED** [review]

**Comment by jdmsoss** [comment]
> Hey @jdmsoss, thanks for calling that out. I didn't realize I was targeting your main branch, so I corrected it to the nsg-flowlogs branch associated to this PR. Please review and merge if you can now.

@oZakari  Oh, right! It's clearer now I understand the issue ^^ PR merged on my side, thx 👍

**Review by oZakari — APPROVED** [review]
LGTM

**Review by ehaslett — APPROVED** [review]
LGTM

**Pull request merged**
