### PR TITLE
feat: Updated KQL for Azure Boost VMs

### PR DESCRIPTION
**Pull request by khushal08**
KQL for Azure Boost

### Breaking Changes
NA

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by ejhenry — COMMENTED** [review]
Thanks @khushal08. Please include a screenshot of the results of your ARG testing in the PR.

**Comment by khushal08** [comment]
azure-boot-aprl
Attaching screenshot from testing

**Comment by ejhenry** [comment]
@khushal08 it is not clear to me how the query aligns with the recommendation. If I read your query correctly, it is retrieving all boost VMs. Queries should retrieve resources that do not align with the recommendation. With this recommendation, we would also need to filter for maintenance sensitive workloads, unless our guidance is to recommend boost for all VMs.

**Comment by khushal08** [comment]
@ejhenry Updated the query to list non boost VMs. The idea is to list VMs for critical maintenance sensitive workloads where Azure Boost is not used. Query has no way to know if the workload is critical maintenance sensitive or not. This is decision needs manual intervention. 
What I suggest is let's go ahead with the query and let WARA CSA take a decision on workload sensitivity.

**Comment by ejhenry** [comment]
> @ejhenry Updated the query to list non boost VMs. The idea is to list VMs for critical maintenance sensitive workloads where Azure Boost is not used. Query has no way to know if the workload is maintenance sensitive or not. This decision needs manual intervention. What I suggest is let's go ahead with the query and let WARA CSA take a decision on workload sensitivity.

@khushal08 queries should not return false positives. In this case it sounds like we should instead note that the recommendation cannot be validated with ARG.

**Comment by khushal08** [comment]
> > @ejhenry Updated the query to list non boost VMs. The idea is to list VMs for critical maintenance sensitive workloads where Azure Boost is not used. Query has no way to know if the workload is maintenance sensitive or not. This decision needs manual intervention. What I suggest is let's go ahead with the query and let WARA CSA take a decision on workload sensitivity.
> 
> @khushal08 queries should not return false positives. In this case it sounds like we should instead note that the recommendation cannot be validated with ARG.

@ejhenry Closing this PR as discussed in ADO item.

**Pull request closed without merging**
