### PR TITLE
fix: Update Virtual Network Gateway query and add new query for TrafficManagerProfiles

### PR DESCRIPTION
**Pull request by rodrigosantosms**
# Overview/Summary

This fix is to prevent any issues with Advisor recommendations using Lower or Upper characters in its recommendation GUIDs.
It also adds a new query for traffic manager profiles, to identify profiles without at least two endpoints in different regions.

### CODE REVIEW

**Review by ehaslett — DISMISSED** [review]
LGTM

**Review by oZakari — DISMISSED** [review]
LGTM

**Comment by davenewman777** [comment]
This worked in my customer environment - Good to go

**Review by davenewman777 — APPROVED** [review]
worked for my customer

**Review by oZakari — APPROVED** [review]

**Pull request merged**
