### PR TITLE
fix: Update Databricks Recommendation List - AB36089

### PR DESCRIPTION
**Pull request by vitaled**
# Overview/Summary

Some of the recommendations in the Databricks Resource were outdated and needed to be updated/removed

- The recommendations about using Photon is not related to the reliability but more on the performance so this PR remove the recommendation from the list
- The recommendations about using Databricks Pools is not considered the best practice for realibility so this PR remove the recommendation from the list
- The recommendations about using Managed Services is considered the best practice for realibility so this PR add the recommendation to the list

## Related Issues/Work Items

Fixes AB#[36089](https://dev.azure.com/CSUSolEng/Well-Architected%20Framework/_workitems/edit/36089)

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by ejhenry — COMMENTED** [review]
Thanks for the contribution @vitaled! The potentialBenefits value for the new recommendation needs to be updated to 60 or less characters.

**Review by davenewman777 — APPROVED** [review]
The changes look good from a technical standpoint. I agree with dropping Photon as it is really only a performance item. The change from Pools to Serverless is also what I was told the PG is recommending. If that is truly the case, then this is good.

**Comment by vitaled** [comment]
> Thanks for the contribution @vitaled! The potentialBenefits value for the new recommendation needs to be updated to 60 or less characters.

Hi @ejhenry thanks for the heads up. Fixed in [57aa700](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pull/480/commits/57aa700fc6e81acf79ac24d0b48366a94b64401e)

**Review by oZakari — APPROVED** [review]
LGTM

**Review by ejhenry — APPROVED** [review]
LGTM

**Pull request merged**
