### PR TITLE
feat: Added filter to applicable VMSS ARG queries to filter out AKS managed VMSSs

### PR DESCRIPTION
**Pull request by judyer28**
# Overview/Summary
A majority of the VMSS ARG queries do not apply to VMSS that are managed by AKS.  This PR adds a filter to applicable ARG queries to filter out AKS managed VMSSs.  The filter looks for a tag "aks-managed-poolName" on the VMSS.  If it is there then it is considered a managed AKS VMSS.  The line below is the filter used to ensure AKS VMSS are not considered as part of the VMSS recommendations.

| where isempty(tostring(tags['aks-managed-poolName']))

## Related Issues/Work Items

Fixes AB#[38580](https://dev.azure.com/CSUSolEng/Azure%20Infra%20Compute/_workitems/edit/38580)

### Breaking Changes

1. _Replace me_
2. _Replace me_

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by judyer28** [comment]
image
image
image
image

**Comment by judyer28** [comment]
image

**Comment by oZakari** [comment]
Thanks @judyer28! LGTM

**Review by oZakari — APPROVED** [review]

**Review by ejhenry — APPROVED** [review]
LGTM

**Pull request merged**
