### PR TITLE
Added recommendation for network watcher connection monitor

### PR DESCRIPTION
**Pull request by khushal08**
# Overview/Summary

Added recommendation for network watcher connection monitor.

### Breaking Changes

NA
## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by ejhenry — COMMENTED** [review]
@khushal08 please address the issues identified in the YAML check.

**Comment by khushal08** [comment]
@ejhenry Done. Can you please let me know if there is any other feedback?

**Comment by ejhenry** [comment]
> @ejhenry Done. Can you please let me know if there is any other feedback?

Thanks @khushal08. This PR also contains file changes for one of the report templates and the sample output files. Can you remove those changes if they were not intended to be a part of the PR?

**Comment by khushal08** [comment]
@ejhenry I am not sure where they came from. I will try to remove them

**Comment by khushal08** [comment]
@ejhenry Done. Any other feedback?

**Review by ehaslett — APPROVED** [review]
LGTM - thanks @khushal08

**Comment by khushal08** [comment]
@ejhenry can you please approve? Merging is blocked.

**Comment by oZakari** [comment]
Hey @khushal08, it looks like you're deleting the existing files. You can run a `git revert <commit id>`

You can see the commit IDs here: https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pull/244/commits. Feel free to ping me if you have questions.

**Review by oZakari — APPROVED** [review]
LGTM

**Pull request merged**
