### PR TITLE
Availability Set to VMSS Flex wording fixed

### PR DESCRIPTION
**Pull request by FallenHoot**
# Overview/Summary

While availability sets are not scheduled for immediate deprecation, they are planned to be deprecated in the future. At this time, no date has been confirmed.

## Related Issues/Work Items

#235 - Fixing wording to make it less confusing

### Breaking Changes

1. No breaking changes. End users can decide if they want to do this now or when the deprecation announcement is officially stated. 

## As part of this pull request I have

- [X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [X] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [NA] Ensured PR tests are passing
- [NA] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [NA] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by ejhenry** [comment]
Recommendation wording has been verified by PG. We will need to check with DRI and PG before making this change.

**Comment by oZakari** [comment]
Hi @michielvanschaik, please review when you get a chance.

**Review by hannah-leland — APPROVED** [review]
The proposed changes look good, there is not a set date for availability set retirement as of now.

**Review by ejhenry — APPROVED** [review]
LGTM

**Pull request merged**
