### PR TITLE
docs: Update Exec Summary PowerPoint deck

### PR DESCRIPTION
**Pull request by davenewman777**
# Overview/Summary

Adding slides to the main WARA powerpoint template to highlight the Advisor process and re-adding the disclaimer slide for CSAs to use if read access has not been granted. 

## Related Issues/Work Items

https://sirona.visualstudio.com/Solutions/_workitems/edit/729955

-->

## As part of this pull request I have

- [x ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x ] Ensured PR tests are passing
- [x ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by kpoineal — APPROVED** [review]

**Comment by kpoineal** [comment]
Approved on my end.

**Comment by tksh164** [comment]
@davenewman777 Which is the latest `Mandatory - Executive Summary presentation - Template.pptx`? There are two files currently, one is in this repo and other one in the IPKIt. The two files are slightly different.

Diffed to repo and IPkit (Framed by green have difference)
image

**Comment by davenewman777** [comment]
@tksh164 

The file in the Repo should be the master. The file in the IP can be updated to match this new version. My intent was to primarily add new files to the tail end of the copy in the Repo. Once these changes are approved, I will update the file in the IP kit

**Comment by tksh164** [comment]
Notes:
- [In this repo](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/main/tools/Mandatory%20-%20Executive%20Summary%20presentation%20-%20Template.pptx) - Last update: 2024-06-25
- In the IPKit - Last update: 2024-08-05

**Comment by davenewman777** [comment]
Other changes coming soon that will impact these changes. Canceling for now and will update again soon

**Pull request closed without merging**
