### PR TITLE
fix: incomplete Service Health alert check points

### PR DESCRIPTION
**Pull request by jdmsoss**
# Overview/Summary

We have detected a certain misalignment regarding the points of attention for this recommendation internally vs. APRL code. Indeed, the KQL code only *"return all subscriptions without Service Health alerts configured"* but we also need to materialize, in the “Impacted Resources” view of the action plan, all Service Health alert rules with a restricted configuration (specific services and/or regions and/or events). Let's take a look below:

## Before

Before, only subscriptions with non-existent Service Health rules were materialized. 

before

## After 

Now, subscriptions with non-existent Service Health rules AND Service Health alert rules with restricted configuration are returned by the code. This will automatically create these entries in the action plan for manual verification, as for other recommendations requiring manual verification and/or special attention.

after-v2

## As part of this pull request I have

- [X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [X] Ensured PR tests are passing
- [X] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by oZakari — DISMISSED** [review]
LGTM

**Comment by jdmsoss** [comment]
Finally, don't approve this PR yet. I can further improve the code before submission 🙂 I'll get back to you once it's ok for approval.

**Comment by jdmsoss** [comment]
> Finally, don't approve this PR yet. I can further improve the code before submission 🙂 I'll get back to you once it's ok for approval.

Code optimization submitted! You can continue with the approval process for this PR 😉

**Review by oZakari — APPROVED** [review]
LGTM

**Review by ejhenry — APPROVED** [review]
LGTM

**Pull request merged**
