### PR TITLE
Fix analyzer script version verification

### PR DESCRIPTION
**Pull request by tksh164**
# Overview/Summary

Fix the analyzer script version verification.

## Related Issues/Work Items

- #149

## This PR fixes/adds/changes/removes

1. Adds `Get-RepoVersion` function to get the latest script versions (the repo version).
2. Fixes the analyzer script version verification with `Get-RepoVersion` function in `Convert-JSON` function.
3. Changes the repo version retrieve method with `Get-RepoVersion` function for consistency in `Set-LocalFile` function.
4. Changes the JSON file outdated message for understandability.

### Breaking Changes

None

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by Claudio-Merola** [comment]
Hi, thanks for contributing.

But you don't need all that to fix this bug, just need to change line 98. 

From that: 

$RepoVersion = Get-Content -Path "$clonePath\tools\Version.json" -ErrorAction SilentlyContinue | ConvertFrom-Json

To that:

$Script:RepoVersion = Get-Content -Path "$clonePath\tools\Version.json" -ErrorAction SilentlyContinue | ConvertFrom-Json

**Comment by tksh164** [comment]
@Claudio-Merola - Thank you for your comment.

Your suggestion will work. But I was concerned about the following points then wrote the current code:

- `$RepoVersion` is used in a few locations such as line 99, 123. So, if change only line 98, it makes for confusing code about the scope of `$RepoVersion` because those lines are not use scope modifier `script:`. (I know that it works without `script:` modifier in this case because there is no local scope variable with the same name. I mean it is not easy to understand).

    https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/3ee5800281733d20f8ad55d28008df3e2e937293/tools/2_wara_data_analyzer.ps1#L99

    https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/3ee5800281733d20f8ad55d28008df3e2e937293/tools/2_wara_data_analyzer.ps1#L123

- [`script:` scope](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes) means "the variable can access from anywhere in the script file". In general, smaller variable's scope is better.

What do you think about the above points?

If `$RepoVersion` to be a script scope variable, I suggest the following changes. Because I think that the wide scope variables should not be defined in the middle of the other codes. It makes the code hard to understand.

```
Add: 24: $Script:RepoVersion = Get-Content -Path "$clonePath\tools\Version.json" -ErrorAction SilentlyContinue | ConvertFrom-Json

Remove: 98: $RepoVersion = Get-Content -Path "$clonePath\tools\Version.json" -ErrorAction SilentlyContinue | ConvertFrom-Json
Change: 99: if ($Version -ne $Script:RepoVersion.Analyzer)

Change: 123: if ($Script:CollectorDetails.Version -eq $Script:RepoVersion.Collector)
```

**Review by oZakari — APPROVED** [review]
This approach makes sense from my perspective, but will wait on @Claudio-Merola to give the go-ahead before we merge.

**Review by Claudio-Merola — APPROVED** [review]
Make sense for making the code less confusing.

**Pull request merged**
