### PR TITLE
AKS Recommendation Updates

### PR DESCRIPTION
**Pull request by ibersanoMS**
# Overview/Summary

1. Added AKS rec 08067d85-962b-4d91-a7ca-c6228e45d5bd about using a Standard LB with the cluster
2. Added AKS rec 9200aca6-0e83-4749-a5eb-e3939367bdc2 about deploying at least 2 replicas of your app
3. Added AKS rec f46b0d1d-56ef-4795-b98a-f6ee00cb341a about using Azure Linux instead of other Linux distributions
4. Removed AKS rec about planning a version upgrade at PG's request because they stated it does not contribute to resiliency. 

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by ibersanoMS** [comment]
AKS - 08067d85-962b-4d91-a7ca-c6228e45d5bd
AKS - f46b0d1d-56ef-4795-b98a-f6ee00cb341a

**Review by ejhenry — COMMENTED** [review]
Thanks @ibersanoMS! For the recommendation to use standard SKU load balancer, are we not already catching that with the same recommendation in Microsoft.Network/loadBalancers recommendation '38c3bca1-97a1-eb42-8cd3-838b243f35ba'?

**Comment by ibersanoMS** [comment]
@ejhenry I included it here because the LB SKU is specified at creation time of the cluster and if they're not using Standard, it would require a change to their AKS deployment

**Comment by ejhenry** [comment]
> @ejhenry I included it here because the LB SKU is specified at creation time of the cluster and if they're not using Standard, it would require a change to their AKS deployment

Thanks @ibersanoMS. We'd like to avoid making the same recommendation more than once on a particular resource. Totally get that there would be different remediation guidance for AKS, but still sounds like it's the same recommendation as the existing LB recommendation. Please ping me if I've misunderstood.

**Comment by ibersanoMS** [comment]
@ejhenry I see what you're saying - I went ahead and removed it.

**Review by ejhenry — APPROVED** [review]
Thanks @ibersanoMS! LGTM 👍

**Review by Dost2010 — APPROVED** [review]

**Pull request merged**
