### PR TITLE
Add ARG query for Azure VM disk encryption

### PR DESCRIPTION
**Pull request by jdmsoss**
# Overview/Summary

Add ARG query for Azure VM disk encryption recommendation (f0a97179-133a-6e4f-8a49-8a44da73ffce) :

aprl_screenshot_20240705

### Breaking Changes

None

## As part of this pull request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/tree/main)
- [ ] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by tksh164** [comment]
Thank you @jdmsoss for contributing to APRL.

I think it is better that VM centric results because this recommendation is for virtual machines. Like as the following:

| name | id | tags | param1 | param2 | param3 |
|----|----|----|----|----|----|
| vm1 | vm1-id | vm1-tags | diskName:vm1-osdisk | EncryptionAtHost: Disabled | DiskEncryption: Disabled |
| vm1 | vm1-id | vm1-tags | diskName:vm1-datadisk1 | EncryptionAtHost: Disabled | DiskEncryption: Disabled |
| vm1 | vm1-id | vm1-tags | diskName:vm1-datadisk2 | EncryptionAtHost: Disabled | DiskEncryption: Disabled |
| vm2 | vm2-id | vm2-tags | diskName:vm2-osdisk | EncryptionAtHost: Disabled | DiskEncryption: Disabled |

Similar cases:
- [Enable Accelerated Networking (AccelNet)](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Compute/virtualMachines/#enable-accelerated-networking-accelnet)
    - The actual settings on network interfaces, but the result is VM centric.
- [VMs should not have a Public IP directly associated](https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Compute/virtualMachines/#vms-should-not-have-a-public-ip-directly-associated)
    - Public IP address settings are on network interfaces, but the result is VM centric.

What do you think?

**Comment by jdmsoss** [comment]
Indeed, it makes sense @tksh164 !
I will update the code this week to produce a result per VM and not per disk. Thank you!

**Comment by jdmsoss** [comment]
> @jdmsoss please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Microsoft"

**Comment by jdmsoss** [comment]
It's seems this PR was automatically updated with two commits from my fork. I didn't find a clean way to remove one of these commit (05bcc65) from this PR for now. What simple method would you suggest for removing this commit from here? 
In the meantime, we can keep commit bd2afe1 which takes into account @tksh164 suggestion 😉
Thank you!

**Comment by tksh164** [comment]
@jdmsoss I think that the most effortless way is to close this PR then re-create a new one.

**Pull request closed without merging**
